locals {
  base = read_terragrunt_config(find_in_parent_folders("_env/env.hcl"))

  project    = local.base.locals.project
  aws_region = local.base.locals.aws_region
  account_id = local.base.locals.account_id

  environment = "dev"

  # Public SPA subdomain. Shared parent zone with the existing secret-share repo's
  # dev subdomain (dev.send-a-secret.link) and the platform integrations
  # (slack-dev., discord-dev.).
  admin_hostname = "admin-dev.send-a-secret.link"
  hosted_zone_id = "Z06715072NF77XVGMB1AG" # send-a-secret.link — owned by the existing secret-share repo

  # Pre-existing SAN cert covering send-a-secret.link + *.send-a-secret.link. Same ARN in prod.
  acm_cert_arn = "arn:aws:acm:us-east-1:081823476824:certificate/d9fbe85b-92c8-4507-bf1d-aaa398224862"

  # Cognito hosted-UI OAuth allowed return URLs. Includes localhost for local SPA dev.
  cognito_callback_urls = [
    "https://admin-dev.send-a-secret.link/auth/callback",
    "http://localhost:3000/auth/callback",
  ]
  cognito_logout_urls = [
    "https://admin-dev.send-a-secret.link/",
    "http://localhost:3000/",
  ]

  # Canary target: the main secret-share dev API. Direct API Gateway call (skip
  # CloudFront) — same reasoning as slack/discord repos: keeps the synthetic in-region
  # with one less TLS handshake. Requires the existing secret-share dev backend
  # to be deployed.
  secret_share_api_base = "https://4wihbmiyq4.execute-api.us-east-1.amazonaws.com/dev"

  # Main app's Lambda log group prefix — used by the activity log + metric filters.
  # Function names are auto-generated by Serverless Framework as
  # `secret-share-backend-${stage}-<functionName>`, so the prefix is deterministic.
  main_app_log_group_prefix = "/aws/lambda/secret-share-backend-dev-"

  # Slack workspace ID that receives alarm DMs from the slack-relay Lambda.
  # The relay looks up this row in the slack repo's workspaces-table to fetch
  # the bot token. Set this to your home workspace's team_id once you've installed
  # the dev Slack app there. Empty = alerts go to console.error only.
  alert_target_team_id = ""

  # Platform integrations the admin reads from. Adding a new platform = add a row.
  # Each row drives: IAM grants for DDB Scan + CloudWatch Logs queries, a metric
  # filter on the install handler, an alarm on the install handler's error rate,
  # and an env var the admin Lambda parses to generically render the install list.
  #
  # Fields:
  #   name                   — short id used in URLs and metric dimensions ("slack", "discord")
  #   display_name           — human label for the SPA ("Slack", "Discord")
  #   table_name             — DynamoDB table holding the installs
  #   table_arn              — full ARN of that table (for IAM)
  #   hash_key               — PK attribute name ("team_id" | "install_id")
  #   display_name_field     — attribute to show as the install label ("team_name" | "guild_name")
  #   type_discriminator     — optional attribute that splits row types ("install_type" for discord; "" if not used)
  #   safe_fields            — allowlist of fields the API will return to the SPA
  #   sensitive_fields       — fields that MUST be stripped (defense in depth — server filters by safe_fields, this is the deny list)
  #   log_group_prefix       — used to scope CWL Insights queries and metric filters to this platform's lambdas
  #   install_handler        — value of `$.handler` in the JSON log line emitted on a successful install
  #   uninstall_handler      — value of `$.handler` on uninstall (empty if platform has no uninstall event)
  #   uninstall_event_type   — value of `$.event_type` on the uninstall log line (empty if N/A)
  platforms = [
    {
      name                 = "slack"
      display_name         = "Slack"
      table_name           = "workspaces-table-dev"
      table_arn            = "arn:aws:dynamodb:us-east-1:081823476824:table/workspaces-table-dev"
      hash_key             = "team_id"
      display_name_field   = "team_name"
      type_discriminator   = ""
      safe_fields          = ["team_id", "team_name", "installed_at", "plan", "installer_user_id", "bot_user_id"]
      sensitive_fields     = ["bot_token"]
      log_group_prefix     = "/aws/lambda/slack-app-"
      install_handler      = "oauth-callback"
      uninstall_handler    = "events"
      uninstall_event_type = "app_uninstalled"
    },
    {
      name                 = "discord"
      display_name         = "Discord"
      table_name           = "installs-table-dev"
      table_arn            = "arn:aws:dynamodb:us-east-1:081823476824:table/installs-table-dev"
      hash_key             = "install_id"
      display_name_field   = "guild_name"
      type_discriminator   = "install_type"
      safe_fields          = ["install_id", "install_type", "guild_name", "installed_at", "plan", "installer_user_id", "bot_user_id"]
      sensitive_fields     = []
      log_group_prefix     = "/aws/lambda/discord-app-"
      install_handler      = "oauth-callback"
      uninstall_handler    = ""
      uninstall_event_type = ""
    },
  ]
}
